class CatalogItem {
  const CatalogItem(this.name, {this.isLarge = false});

  final String name;
  final bool isLarge;
}

const roomCatalog = <String, List<CatalogItem>>{
  'מטבח': [
    CatalogItem('מקרר', isLarge: true),
    CatalogItem('מקפיא', isLarge: true),
    CatalogItem('תנור', isLarge: true),
    CatalogItem('כיריים'),
    CatalogItem('קולט אדים', isLarge: true),
    CatalogItem('מדיח', isLarge: true),
    CatalogItem('מיקרוגל'),
    CatalogItem('מיקסר'),
    CatalogItem('מעבד מזון'),
    CatalogItem('בלנדר'),
    CatalogItem('בלנדר מוט'),
    CatalogItem('קומקום'),
    CatalogItem('טוסטר'),
    CatalogItem('טוסטר אובן'),
    CatalogItem('מכונת קפה'),
    CatalogItem('מקציף חלב'),
    CatalogItem('סודה סטרים'),
    CatalogItem('אייר פרייר'),
    CatalogItem('סיר לחץ'),
    CatalogItem('סיר בישול איטי'),
    CatalogItem('גריל חשמלי'),
    CatalogItem('משקל מטבח'),
    CatalogItem('סירים'),
    CatalogItem('מחבתות'),
    CatalogItem('מכסים'),
    CatalogItem('תבניות אפייה'),
    CatalogItem('כלי אפייה'),
    CatalogItem('קערות ערבוב'),
    CatalogItem('צלחות'),
    CatalogItem('קעריות'),
    CatalogItem('כוסות'),
    CatalogItem('ספלים'),
    CatalogItem('כוסות יין'),
    CatalogItem('סכו״ם'),
    CatalogItem('סכיני מטבח'),
    CatalogItem('קרשי חיתוך'),
    CatalogItem('כלי הגשה'),
    CatalogItem('קופסאות אחסון'),
    CatalogItem('צנצנות'),
    CatalogItem('בקבוקים'),
    CatalogItem('מגבות מטבח'),
    CatalogItem('מפות שולחן'),
    CatalogItem('מוצרי מזון יבשים'),
    CatalogItem('תבלינים'),
    CatalogItem('חומרי ניקוי'),
    CatalogItem('פח אשפה'),
    CatalogItem('שולחן אוכל', isLarge: true),
    CatalogItem('כיסאות אוכל', isLarge: true),
    CatalogItem('אי מטבח', isLarge: true),
  ],
  'סלון': [
    CatalogItem('ספה', isLarge: true),
    CatalogItem('כורסה', isLarge: true),
    CatalogItem('הדום', isLarge: true),
    CatalogItem('טלוויזיה', isLarge: true),
    CatalogItem('מזנון', isLarge: true),
    CatalogItem('שולחן סלון', isLarge: true),
    CatalogItem('שולחן צד', isLarge: true),
    CatalogItem('ספרייה', isLarge: true),
    CatalogItem('ויטרינה', isLarge: true),
    CatalogItem('שידה', isLarge: true),
    CatalogItem('שטיח'),
    CatalogItem('וילונות'),
    CatalogItem('כריות נוי'),
    CatalogItem('שמיכות'),
    CatalogItem('מנורת רצפה'),
    CatalogItem('מנורות שולחן'),
    CatalogItem('רמקולים'),
    CatalogItem('סאונדבר'),
    CatalogItem('ממיר'),
    CatalogItem('קונסולת משחקים'),
    CatalogItem('שלטים'),
    CatalogItem('כבלים'),
    CatalogItem('ראוטר'),
    CatalogItem('ספרים'),
    CatalogItem('משחקי קופסה'),
    CatalogItem('תמונות'),
    CatalogItem('מסגרות'),
    CatalogItem('פסלים וקישוטים'),
    CatalogItem('אגרטלים'),
    CatalogItem('עציצים'),
    CatalogItem('שעון קיר'),
    CatalogItem('מאוורר', isLarge: true),
    CatalogItem('מזגן נייד', isLarge: true),
  ],
  'חדר שינה': [
    CatalogItem('מיטה', isLarge: true),
    CatalogItem('מזרן', isLarge: true),
    CatalogItem('בסיס מיטה', isLarge: true),
    CatalogItem('ארון', isLarge: true),
    CatalogItem('שידות לילה', isLarge: true),
    CatalogItem('שידת מגירות', isLarge: true),
    CatalogItem('שולחן איפור', isLarge: true),
    CatalogItem('מראה', isLarge: true),
    CatalogItem('טלוויזיה', isLarge: true),
    CatalogItem('בגדים'),
    CatalogItem('מעילים'),
    CatalogItem('נעליים'),
    CatalogItem('תיקים'),
    CatalogItem('מצעים'),
    CatalogItem('שמיכות'),
    CatalogItem('כריות'),
    CatalogItem('מגבות'),
    CatalogItem('תכשיטים'),
    CatalogItem('מוצרי טיפוח'),
    CatalogItem('ספרים'),
    CatalogItem('מנורות'),
    CatalogItem('וילונות'),
    CatalogItem('שטיח'),
    CatalogItem('מאוורר'),
    CatalogItem('מטענים וכבלים'),
  ],
  'חדר ילדים': [
    CatalogItem('מיטה', isLarge: true),
    CatalogItem('מזרן', isLarge: true),
    CatalogItem('ארון', isLarge: true),
    CatalogItem('שידת החתלה', isLarge: true),
    CatalogItem('שולחן', isLarge: true),
    CatalogItem('כיסא', isLarge: true),
    CatalogItem('ספרייה', isLarge: true),
    CatalogItem('כוורת', isLarge: true),
    CatalogItem('צעצועים'),
    CatalogItem('משחקי קופסה'),
    CatalogItem('לגו וקוביות'),
    CatalogItem('בובות'),
    CatalogItem('מכוניות צעצוע'),
    CatalogItem('ספרים'),
    CatalogItem('ציוד לימודי'),
    CatalogItem('מחברות וכלי כתיבה'),
    CatalogItem('בגדים'),
    CatalogItem('נעליים'),
    CatalogItem('מצעים'),
    CatalogItem('שמיכות'),
    CatalogItem('תיקי בית ספר'),
    CatalogItem('אופניים', isLarge: true),
    CatalogItem('קורקינט', isLarge: true),
    CatalogItem('מחשב או טאבלט'),
    CatalogItem('קונסולת משחקים'),
    CatalogItem('מנורת לילה'),
    CatalogItem('קישוטים ותמונות'),
  ],
  'אמבטיה': [
    CatalogItem('מכונת כביסה', isLarge: true),
    CatalogItem('מייבש כביסה', isLarge: true),
    CatalogItem('ארונית אמבטיה', isLarge: true),
    CatalogItem('סל כביסה', isLarge: true),
    CatalogItem('מראה'),
    CatalogItem('מגבות גוף'),
    CatalogItem('מגבות ידיים'),
    CatalogItem('שטיחי אמבטיה'),
    CatalogItem('וילון אמבטיה'),
    CatalogItem('מוצרי רחצה'),
    CatalogItem('מוצרי טיפוח'),
    CatalogItem('מוצרי שיער'),
    CatalogItem('מייבש שיער'),
    CatalogItem('מחליק או מסלסל'),
    CatalogItem('מכונת גילוח'),
    CatalogItem('מברשות שיניים'),
    CatalogItem('תרופות'),
    CatalogItem('חומרי ניקוי'),
    CatalogItem('נייר טואלט'),
    CatalogItem('אביזרי כביסה'),
    CatalogItem('מתלים ומדפים'),
  ],
  'מחסן': [
    CatalogItem('אופניים', isLarge: true),
    CatalogItem('קורקינט', isLarge: true),
    CatalogItem('סולם', isLarge: true),
    CatalogItem('מדפים', isLarge: true),
    CatalogItem('ארון אחסון', isLarge: true),
    CatalogItem('ארגזי כלים'),
    CatalogItem('כלי עבודה ידניים'),
    CatalogItem('מקדחה'),
    CatalogItem('מברגה'),
    CatalogItem('מסור'),
    CatalogItem('ברגים ומסמרים'),
    CatalogItem('כבלים מאריכים'),
    CatalogItem('צבעים וחומרי שיפוץ'),
    CatalogItem('ציוד גינה'),
    CatalogItem('ציוד קמפינג'),
    CatalogItem('מזוודות'),
    CatalogItem('קישוטי חגים'),
    CatalogItem('מאווררים'),
    CatalogItem('תנורי חימום'),
    CatalogItem('ציוד ספורט'),
    CatalogItem('ציוד ים ובריכה'),
    CatalogItem('מוצרי ניקוי'),
    CatalogItem('מלאי מזון'),
    CatalogItem('נורות וחלקי חילוף'),
  ],
  'חדר עבודה': [
    CatalogItem('שולחן עבודה', isLarge: true),
    CatalogItem('כיסא משרדי', isLarge: true),
    CatalogItem('ספרייה', isLarge: true),
    CatalogItem('ארון מסמכים', isLarge: true),
    CatalogItem('מחשב נייח'),
    CatalogItem('מחשב נייד'),
    CatalogItem('מסכים'),
    CatalogItem('תחנת עגינה'),
    CatalogItem('מקלדות'),
    CatalogItem('עכברים'),
    CatalogItem('מדפסת'),
    CatalogItem('סורק'),
    CatalogItem('ראוטר וציוד רשת'),
    CatalogItem('כבלים ומתאמים'),
    CatalogItem('מטענים'),
    CatalogItem('אוזניות'),
    CatalogItem('מצלמה ומיקרופון'),
    CatalogItem('רמקולים'),
    CatalogItem('אל פסק'),
    CatalogItem('מסמכים'),
    CatalogItem('קלסרים'),
    CatalogItem('ספרים'),
    CatalogItem('ציוד משרדי'),
    CatalogItem('נייר למדפסת'),
    CatalogItem('מנורת שולחן'),
  ],
};

List<CatalogItem> catalogForRoom(String roomName) {
  final exact = roomCatalog[roomName];
  if (exact != null) {
    return exact;
  }
  if (roomName.contains('שינה')) {
    return roomCatalog['חדר שינה']!;
  }
  if (roomName.contains('ילד')) {
    return roomCatalog['חדר ילדים']!;
  }
  if (roomName.contains('עבודה') || roomName.contains('משרד')) {
    return roomCatalog['חדר עבודה']!;
  }
  return const [];
}
